blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'
urlpatterns =[
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

temp_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Online Market"
admin.site.index_title = "Hush kelibsiz !..."

urlpatterns = ([
                   path('admin/', admin.site.urls),
                    path('blogs/', include('blogs.urls', namespace='blogs')),
                    path('products/', include('products.urls', namespace='products')),
                    path('users/', include('users.urls', namespace='users')),
                   path('', include('pages.urls', namespace='pages')),
               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                            document_root=settings.
                                                                                            MEDIA_ROOT))

blogs/models.py
from django.db import models


class AuthorModel(models.Model):
    objects = None
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='blog-authors')
    about = models.TextField()
    position = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['position']
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'


class BlogCategoryModel(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class BlogTagModel(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogModel(models.Model):
    objects = None
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='blog-images')
    short_info = models.TextField(null=True)
    content = models.TextField()
    category = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='tags')
    author = models.ForeignKey(AuthorModel, on_delete=models.CASCADE, related_name='blogs')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

blogs/views.py
from django.views.generic import ListView, DetailView

from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel, AuthorModel


class BlogListView(ListView):
    template_name = 'blogs/blog-list.html'
    context_object_name = 'blogs'
    paginate_by = 2

    def get_queryset(self):
        qs = BlogModel.objects.all().order_by('-pk')
        cat = self.request.GET.get('cat')
        tag = self.request.GET.get('tag')

        if cat:
            qs = qs.filter(category__in=cat)
        if tag:
            qs = qs.filter(tags__in=tag)

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = BlogCategoryModel.objects.all()
        context['tags'] = BlogTagModel.objects.all()
        context['famous_blogs'] = BlogModel.objects.all().order_by('-created_at')[:2]

        return context


class BlogDetailView(DetailView):
    template_name = 'blogs/blog-detail.html'
    context_object_name = 'blogs'
    model = BlogModel

    def get_object(self, *args, **kwargs):
        return BlogModel.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "author": AuthorModel.objects.all(),
            "blog": BlogModel.objects.get(pk=self.kwargs['pk']),
            "category": BlogCategoryModel.objects.all(),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('-created_at')[:3],
            "related_blogs": BlogModel.objects.filter(category__in=self.object.category.all())[:3]
        }
        return context

templates/blogs/blog-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">
                <div id="main">
                    <div class="page-home">

                        <!-- breadcrumb -->
                        <nav class="breadcrumb-bg">
                            <div class="container no-index">
                                <div class="breadcrumb">
                                    <ol>
                                        <li>
                                            <a href="#">
                                                <span>Home</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Living Room</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Sofa</span>
                                            </a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </nav>
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    <div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                        <!-- category -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Categories</div>
                                            <div class="block-content">
                                                {% for cat in category %}
                                                <div class="cateTitle hasSubCategory open level1">
                                                    <a class="cateItem" href="#">{{ cat.name }}</a>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- recent posts -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Recent Posts</div>
                                            <div class="post-item-content">
                                                {% for blog in famous_blogs %}
                                                <div>
                                                    <div class="late-item first-child">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                            <p class="content-title">{{ blog.title }}</p>
                                                        </a>
                                                        <span>
                                                            <i class="zmdi zmdi-comments"></i>13 comment
                                                        </span>
                                                        <span>
                                                            <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at }}
                                                        </span>
                                                        <p class="description">{{blog.short_info}}
                                                        </p>
                                                        <p class="remove">
                                                            <a href="{% url 'blogs:detail' pk=blog.id %}">READ MORE</a>
                                                        </p>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- product tag -->
                                        <div class="sidebar-block product-tags">
                                            <div class="title-block">
                                                Blog Tags
                                            </div>
                                            <div class="block-content">
                                                <ul class="listSidebarBlog list-unstyled">
                                                    {% for tag in tags %}
                                                    <li>
                                                        <a href="#" title="Show products matching tag Hot Trend">{{ tag.name }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>

                                        <!-- advertising -->
                                        <div class="sidebar-block group-image-special">
                                            <div class="effect">
                                                <a href="#">
                                                    <img class="img-fluid" src="{% static 'img/blog/advertising.jpg' %}" alt="banner-2" title="banner-2">
                                                </a>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                        <h3>{{ blog.title }}</h3>
                                        <div class="hover-after">
                                            <img src="{{ blog.image.url }}" alt="img" class="img-fluid">
                                        </div>
                                        <div class="late-item">
                                            <p>
                                                {{ blog.content }}
                                            </p>
                                            <p>
                                            <div class="border-detail">
                                                <p class="post-info float-left">
                                                    <span>{{ blog.created_at }}</span>
                                                    <span>113 Comments</span>
                                                    <span>{{ blog.author.name }}</span>
                                                </p>
                                                <div class="btn-group">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-share"></i>
                                                        <span>Share</span>
                                                    </a>
                                                    <a href="#" class="email">
                                                        <i class="fa fa-envelope" aria-hidden="true"></i>
                                                        <span>SEN TO A FRIEND</span>
                                                    </a>
                                                    <a href="#" class="print">
                                                        <i class="zmdi zmdi-print"></i>
                                                        <span>Print</span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="admin">
                                            <img src="{{ blog.author.image.url }}" alt="img" class="float-left right">
                                            <div class="info">
                                                <p>
                                                    <a href="#">
                                                        <span class="content-title">
                                                            {{ blog.author.name }}
                                                        </span>
                                                    </a>
                                                    <span>{{ blog.author.position }}, {{ blog.author.profession }}</span>
                                                </p>
                                                <p class="descript">
                                                   {{ blog.author.about }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="related">
                                            <h2 class="title-block">Related News</h2>
                                            <div class="main-blogs">
                                                <div class="row">
                                                    {% for blog in related_blogs %}
                                                    <div class="col-md-4">
                                                        <div class="hover-after">
                                                            <a href="blog-detail.html">
                                                                <img src="{{ blog.image.url }}" alt="img" class="img-fluid">
                                                            </a>
                                                        </div>
                                                        <div class="late-item">
                                                            <p class="content-title">
                                                                <a href="blog-detail.html">{{ blog.title }}</a>
                                                            </p>
                                                            <p class="description">{{ blog.short_info }}
                                                            </p>
                                                        </div>
                                                    </div>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blogs/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">
                <div id="main">
                    <div class="page-home">

                        <!-- breadcrumb -->
                        <nav class="breadcrumb-bg">
                            <div class="container no-index">
                                <div class="breadcrumb">
                                    <ol>
                                        <li>
                                            <a href="#">
                                                <span>Home</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Living Room</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Sofa</span>
                                            </a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </nav>
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    <div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                        <!-- category -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Categories</div>
                                            <div class="block-content">
                                                {% for cat in categories %}
                                                <div class="cateTitle hasSubCategory open level1">
                                                    <a style="cursor: pointer" class="cateItem" onclick="addUrlParameter('cat','{{ cat.pk }}')">{{ cat.name }}</a>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- recent posts -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Recent Posts</div>
                                            <div class="post-item-content">
                                                {% for blog in famous_blogs %}
                                                <div>
                                                    <div class="late-item first-child">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                            <p class="content-title">{{ blog.title }}</p>
                                                        </a>
                                                        <span>
                                                            <i class="zmdi zmdi-comments"></i>13 comment
                                                        </span>
                                                        <span>
                                                            <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at }}
                                                        </span>
                                                        <p class="description">{{blog.short_info}}
                                                        </p>
                                                        <p class="remove">
                                                            <a href="{% url 'blogs:detail' pk=blog.id %}">READ MORE</a>
                                                        </p>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        

                                        <!-- product tag -->
                                        <div class="sidebar-block product-tags">
                                            <div class="title-block">
                                                Blog Tags
                                            </div>
                                            <div class="block-content">
                                                <ul class="listSidebarBlog list-unstyled">
                                                    {% for tag in tags %}
                                                    <li>
                                                        <a style="cursor: pointer" onclick="addUrlParameter('tag','{{ tag.pk }}')"
                                                           title="Show products matching tag Hot Trend">{{ tag.name }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>

                                        <!-- advertising -->
                                        <div class="sidebar-block group-image-special">
                                            <div class="effect">
                                                <a href="#">
                                                    <img class="img-fluid" src="{% static 'img/blog/advertising.jpg' %}" alt="banner-2" title="banner-2">
                                                </a>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                        <h2>Recent Posts</h2>
                                        {% for blog in blogs %}
                                        <div class="list-content row">
                                            <div class="hover-after col-md-5 col-xs-12">
                                                <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                    <img src="{{ blog.image.url }}" alt="img">
                                                </a>
                                            </div>
                                            <div class="late-item col-md-7 col-xs-12">
                                                <p class="content-title">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">{{ blog.title }}</a>
                                                </p>
                                                <p class="post-info">
                                                    <span>{{ blog.created_at }}</span>
                                                    <span>113 Comments</span>
                                                    <span>{{blog.author.name}}</span>
                                                </p>
                                                <p class="description">{{blog.short_info}}
                                                </p>
                                                <span class="view-more">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">view more</a>
                                                </span>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        <div class="page-list col">
                                            <ul class="justify-content-center d-flex">
                                                {% if page_obj.has_previous %}
                                                <li>
                                                    <a rel="prev" href="?page={{ page_obj.previous_page_number }}" class="previous disabled js-search-link">
                                                        Previous
                                                    </a>
                                                </li>
                                                {% endif %}
                                                {% for page in page_obj.paginator.page_range %}
                                                <li {% if page == page_obj.number %} class="current active">{% endif %}
                                                    <a rel="nofollow" href="?page={{ page }}" class="disabled js-search-link">
                                                        1
                                                    </a>
                                                </li>
                                                {% endfor %}
                                                {% if page_obj.has_next %}
                                                <li>
                                                    <a rel="next" href="?page={{ page_obj.next_page_number }}" class="next disabled js-search-link">
                                                        Next
                                                    </a>
                                                </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        function addUrlParameter(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            if (searchParams.has(name) && searchParams.get(name) === value) {
                searchParams.delete(name)
            } else {
                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }
    </script>
{% endblock %}